services:
  postgres:
    image: postgres:16-alpine
    container_name: bitetrack_pgdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - bitetrack_data:/var/lib/postgresql/data
volumes:
  bitetrack_data:
